sudo: required
language: c

services:
  - docker

before_install:
  - docker pull hangpark/pintos-dev-env-kaist

script:
  - docker run -v $TRAVIS_BUILD_DIR:/pintos hangpark/pintos-dev-env-kaist /bin/bash -c "export PATH=$PATH:/pintos/src/utils && cd /pintos/src/$TARGET_DIRECTORY && make grade" > temp && rm temp && cat src/$TARGET_DIRECTORY/build/grade
