sudo: required
language: c

services:
  - docker

before_install:
  - docker pull kanglib/pintos-kaist-qemu

script:
  - docker run -v $TRAVIS_BUILD_DIR:/pintos kanglib/pintos-kaist-qemu
    sh -c "make -C src/$TARGET_DIRECTORY grade"
