sudo: required
language: c

services:
  - docker

before_install:
  - docker pull hangpark/pintos-dev-env-kaist

script:
  - docker run -v $TRAVIS_BUILD_DIR:/pintos hangpark/pintos-dev-env-kaist
    sh -c "make -C src/$TARGET_DIRECTORY grade"
